### ISSUE TITLE
Screen resolution doesn't change but can be revert

### ISSUE THREAD

**Issue by daydreamingdude** [Nonary/ResolutionAutomation#52] opened 2024-01-18 03:58 UTC
I installed the new version but no screen resolution changing occurs when moonlight launches sunlight. However, if I adjust the resolution in ResolutionMatcher-Functions.ps1, it will execute a change to whatever resolution I specify in that file. 

I am going to paste my log when launch the script with default Functions.ps1, and then a modified Functions.ps1 that specifies a 1280x800x60 resolution.

**Default:**

```
**********************
Windows PowerShell transcript start
Start time: 20240117195254
Username: DESKTOP-9G89AQC\Barrett
RunAs User: DESKTOP-9G89AQC\Barrett
Configuration Name: 
Machine: DESKTOP-9G89AQC (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\ResolutionMatcher\ResolutionMatcher.ps1 -async True
Process ID: 1868
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 2560 x 1440 x 144
Resolution changed successfully.
**********************
Windows PowerShell transcript end
End time: 20240117195302
**********************
```

**1280x800x60:**

```
**********************
Windows PowerShell transcript start
Start time: 20240117195459
Username: DESKTOP-9G89AQC\Barrett
RunAs User: DESKTOP-9G89AQC\Barrett
Configuration Name: 
Machine: DESKTOP-9G89AQC (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\ResolutionMatcher\ResolutionMatcher.ps1 -async True
Process ID: 9548
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Current Resolution: 2560 x 1440 x 144
Expected Requested Resolution:  x  x
Setting screen resolution to  x  x
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 1280 x 800 x 60
Resolution changed successfully.
**********************
Windows PowerShell transcript end
End time: 20240117195508
**********************

```
Not sure what's happening here. I've uninstalled and reinstalled, set it to be elevated with admin permissions, but nothing executes. Setting the override to 1280x800x60=1280x800x60 does nothing as well. Honestly I don't see why we can't just define the resolution in the first powershell script like we can in the one that reverts.

**Comment by VeeTeg** [comment] 2024-01-20 09:19
I am experiencing the exact same issue.  SteamDeck>Moonlight>Sunlight

Can you walk me through what text you changed in ResolutionMatcher-Functions.ps1?

**Comment by Germican12** [comment] 2024-01-21 23:03
Im having the same issue on moonlight/sunshine. Log as follows:
`
Process ID: 20932
PSVersion: 5.1.22000.2538
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22000.2538
BuildVersion: 10.0.22000.2538
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Current Resolution: 5120 x 1440 x 60
Expected Requested Resolution: 1280 x 800 x 45
Setting screen resolution to 1280 x 800 x 45
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 5120 x 1440 x 60
Resolution changed successfully.
**********************
Windows PowerShell transcript end
End time: 20240121235616
**********************`

**Comment by FuzzyMistborn** [comment] 2024-01-22 14:30
Same issue, reverting to [v2.2.0](https://github.com/Nonary/ResolutionAutomation/releases/tag/2.2.0) fixes the issue for now.

**Comment by Nonary** [comment] 2024-01-23 15:55
> Same issue, reverting to [v2.2.0](https://github.com/Nonary/ResolutionAutomation/releases/tag/2.2.0) fixes the issue for now.

Your issue is not the same please open a new issue with logs.

**Comment by Nonary** [comment] 2024-01-23 15:56
> Im having the same issue on moonlight/sunshine. Log as follows: ` Process ID: 20932 PSVersion: 5.1.22000.2538 PSEdition: Desktop PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22000.2538 BuildVersion: 10.0.22000.2538 CLRVersion: 4.0.30319.42000 WSManStackVersion: 3.0 PSRemotingProtocolVersion: 2.3 SerializationVersion: 1.1.0.1
> 
> Transcript started, output file is .\log.txt
> 
> Id Name PSJobTypeName State HasMoreData Location Command
> 
> 1 ResolutionMa... BackgroundJob Running True localhost ... 3 ResolutionMa... BackgroundJob Running True localhost ... Waiting for the next event to be called... (for starting/ending stream) Processing event: Start Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Current Resolution: 5120 x 1440 x 60 Expected Requested Resolution: 1280 x 800 x 45 Setting screen resolution to 1280 x 800 x 45 Request to terminate has been processed, script will now revert resolution. Setting screen resolution to 5120 x 1440 x 60 Resolution changed successfully.
> 
> Windows PowerShell transcript end End time: 20240121235616 **********************`

You need to add 1280 x 800 x 45 to your custom resolutions using NVIDIA Control Panel or CRU.

**Comment by Nonary** [comment] 2024-01-23 15:57
> I installed the new version but no screen resolution changing occurs when moonlight launches sunlight. However, if I adjust the resolution in ResolutionMatcher-Functions.ps1, it will execute a change to whatever resolution I specify in that file.
> 
> I am going to paste my log when launch the script with default Functions.ps1, and then a modified Functions.ps1 that specifies a 1280x800x60 resolution.
> 
> **Default:**
> 
> ```
> **********************
> Windows PowerShell transcript start
> Start time: 20240117195254
> Username: DESKTOP-9G89AQC\Barrett
> RunAs User: DESKTOP-9G89AQC\Barrett
> Configuration Name: 
> Machine: DESKTOP-9G89AQC (Microsoft Windows NT 10.0.22631.0)
> Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\ResolutionMatcher\ResolutionMatcher.ps1 -async True
> Process ID: 1868
> PSVersion: 5.1.22621.2506
> PSEdition: Desktop
> PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
> BuildVersion: 10.0.22621.2506
> CLRVersion: 4.0.30319.42000
> WSManStackVersion: 3.0
> PSRemotingProtocolVersion: 2.3
> SerializationVersion: 1.1.0.1
> **********************
> Transcript started, output file is .\log.txt
> 
> Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
> --     ----            -------------   -----         -----------     --------             -------
> 1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
> 3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
> Waiting for the next event to be called... (for starting/ending stream)
> Processing event: Start
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Request to terminate has been processed, script will now revert resolution.
> Setting screen resolution to 2560 x 1440 x 144
> Resolution changed successfully.
> **********************
> Windows PowerShell transcript end
> End time: 20240117195302
> **********************
> ```
> 
> **1280x800x60:**
> 
> ```
> **********************
> Windows PowerShell transcript start
> Start time: 20240117195459
> Username: DESKTOP-9G89AQC\Barrett
> RunAs User: DESKTOP-9G89AQC\Barrett
> Configuration Name: 
> Machine: DESKTOP-9G89AQC (Microsoft Windows NT 10.0.22631.0)
> Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\ResolutionMatcher\ResolutionMatcher.ps1 -async True
> Process ID: 9548
> PSVersion: 5.1.22621.2506
> PSEdition: Desktop
> PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
> BuildVersion: 10.0.22621.2506
> CLRVersion: 4.0.30319.42000
> WSManStackVersion: 3.0
> PSRemotingProtocolVersion: 2.3
> SerializationVersion: 1.1.0.1
> **********************
> Transcript started, output file is .\log.txt
> 
> Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
> --     ----            -------------   -----         -----------     --------             -------
> 1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
> 3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
> Waiting for the next event to be called... (for starting/ending stream)
> Processing event: Start
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Current Resolution: 2560 x 1440 x 144
> Expected Requested Resolution:  x  x
> Setting screen resolution to  x  x
> Request to terminate has been processed, script will now revert resolution.
> Setting screen resolution to 1280 x 800 x 60
> Resolution changed successfully.
> **********************
> Windows PowerShell transcript end
> End time: 20240117195508
> **********************
> ```
> 
> Not sure what's happening here. I've uninstalled and reinstalled, set it to be elevated with admin permissions, but nothing executes. Setting the override to 1280x800x60=1280x800x60 does nothing as well. Honestly I don't see why we can't just define the resolution in the first powershell script like we can in the one that reverts.

Your Sunshine version is likely not the correct version, you need to be on at least 0.20 or higher since it supports the environment variables which passes in information such as resolution and framerate. Since the logs show that it is empty, that implies to me you are not on the correct Sunshine version.

**Comment by FuzzyMistborn** [comment] 2024-01-23 15:58
Ok, seems to be the same because I was having the identical issue with the latest release (logs are identical to the OP with `Expected Requested Resolution:  x  x`).

**Comment by Nonary** [comment] 2024-01-23 16:04
Duplicate of #51

**Closed by Nonary** 2024-01-23 16:04 UTC

**Comment by OMGrant** [comment] 2024-01-23 17:51
I too am on the latest version of Sunshine. Please reopen. 
![image](https://github.com/Nonary/ResolutionAutomation/assets/10854023/ec6c113b-6bd4-4de2-abe8-a87b29cf23cf)
